<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><OutputType>Exe</OutputType><RestorePackagesWithLockFile>true</RestorePackagesWithLockFile></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/JotBloom.Windows.Storage/JotBloom.Windows.Storage.csproj" /></ItemGroup>
</Project>
