<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseAppHost>true</UseAppHost>
    <AssemblyName>JotBloom</AssemblyName>
    <Version>1.0.3</Version>
    <InformationalVersion>1.0.3 测试版</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <FileVersion>1.0.3.1</FileVersion>
    <AssemblyVersion>1.0.3.0</AssemblyVersion>
    <Product>萌生 · JotBloom</Product>
    <Company>FengLi-AI</Company>
    <ApplicationIcon>Assets/JotBloom.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <StartupObject>JotBloom.Windows.Desktop.Program</StartupObject>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.12" />
    <ProjectReference Include="../JotBloom.Windows.Core/JotBloom.Windows.Core.csproj" />
    <ProjectReference Include="../JotBloom.Windows.Storage/JotBloom.Windows.Storage.csproj" />
  </ItemGroup>
</Project>
